/*
 * generated by Xtext 2.38.0
 */
package org.xtext.robotdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.robotdsl.RobotDslRuntimeModule;
import org.xtext.robotdsl.RobotDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RobotDslIdeSetup extends RobotDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RobotDslRuntimeModule(), new RobotDslIdeModule()));
	}
	
}
