/*
 * generated by Xtext 2.38.0
 */
package org.xtext.robotdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RobotDslUiModule extends AbstractRobotDslUiModule {

	public RobotDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
