/*
 * generated by Xtext 2.38.0
 */
package org.xtext.robotdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RobotDslStandaloneSetup extends RobotDslStandaloneSetupGenerated {

	public static void doSetup() {
		new RobotDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
