/*
 * generated by Xtext 2.38.0
 */
package org.xtext.robotdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RobotDslRuntimeModule extends AbstractRobotDslRuntimeModule {
}
